package com.example.kafkaeventalarm.consumer;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Service;

import com.example.kafkaeventalarm.Constants;
import com.example.kafkaeventalarm.model.Order;

@Service
public class GeneratedOrderConsumer {
    private final Logger logger = LoggerFactory.getLogger(GeneratedOrderConsumer.class);

    @KafkaListener(topics = "#{'${autogenerated-order.topic.name}'.split(',')}", groupId = Constants.GROUP_ID, containerFactory = "orderGeneratedKafkaListenerContainerFactory")
    public void consume(Order order) {
       logger.info(String.format("Order consumed (from GeneratedOrder Producer)-> %s", order));
   }
}
